# Generated by Django 4.1.4 on 2022-12-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuser',
            name='age',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
