# Generated by Django 4.1.4 on 2022-12-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_aboutuser_academy_delete_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuser',
            name='experience',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
