# Generated by Django 4.1.4 on 2022-12-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='college',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
